#pragma once

typedef enum Error {
    ERROR_IO = 1,

    ERROR_INVALID_FORMAT,
    ERROR_OUT_OF_MEMORY,
    ERROR_OUT_OF_BOUNDS,

    ERROR_INVALID_ARGUMENTS,

    ERROR_BACKEND_UNKNOWN,
    ERROR_SHADER_COMPILATION_FAILED,
    ERROR_SHADER_LOADING_FAILED,
    ERROR_UNIFORM_NOT_FOUND,

    ERROR_INVALID_PLUGIN,

    ERROR_UNSUPPORTED,
} Error;

void error_print(char const *scope, int retval);
