#pragma once

enum error {
    ERROR_IO = 1,
    ERROR_INVALID_FORMAT,
    ERROR_RINGBUFFER_PTR_OVERRUN,
    ERROR_INVALID_ARGUMENTS,
    ERROR_UNIFORM_NOT_FOUND,
    ERROR_OUT_OF_MEMORY,
    ERROR_OUT_OF_BOUNDS,
    ERROR_SHADER_COMPILATION_FAILED,
    ERROR_SHADER_LOADING_FAILED,
    ERROR_BACKEND_UNKNOWN,
};

void error_print(char const *scope, int retval);
